name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cappello-parlante-environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t .  

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CP }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CP }}
        aws-region: eu-central-1

    - name: Download and extract ImageMagick binaries
      run: |
        git clone https://github.com/serverlesspub/imagemagick-aws-lambda-2.git
        cd imagemagick-aws-lambda-2
        make all
        cp -r result ../

    - name: Prepare deployment package
      run: |
        zip -r function.zip .  # Include all files in the current directory

    - name: Deploy to AWS Lambda
      run: |
        pip install awscli
        aws lambda update-function-code --function-name cappello-parlante --zip-file fileb://function.zip